apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-virtual-host-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: k8s.eu
    http:
      paths:
      - backend:
          serviceName: timber-frontend
          servicePort: 8080
  - host: k8s.eu
    http:
      paths:
      - backend:
          serviceName: timber-backend
          servicePort: 8080