apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ngx-fanout-ing
spec:
  rules:
  - host: u1.timber.training.csol.cloud
    http:
      paths:
      - path: /
        backend:
          serviceName: timber-frontend
          servicePort: 8080
      - path: /api
        backend:
          serviceName: timber-backend
          servicePort: 8080