apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ngx-virtual-host-ing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: front.u1.timber.training.csol.cloud
    http:
      paths:
      - backend:
          serviceName: timber-frontend
          servicePort: 8080
  - host: back.u1.timber.training.csol.cloud
    http:
      paths:
      - backend:
          serviceName: timber-backend
          servicePort: 8080