apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /frontend/?(.*)
        backend:
          serviceName: timber-frontend
          servicePort: 8080
      - path: /backend/?(.*)
        backend:
          serviceName: timber-backend
          servicePort: 8080        
