apiVersion: apps/v1
kind: Deployment
metadata:
  name: quota-demo
  labels:
    app: quota-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quota-demo
  template:
    metadata:
      labels:
        app: quota-demo
    spec:
      containers:
        - name: resource-consumer
          image: gcr.io/kubernetes-e2e-test-images/resource-consumer:1.4
          resources:
            requests:
              cpu: "100m"
              memory: "250Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"