apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: stress-demo-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stress-demo
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 33
