apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-demo
spec:
  hard:
    requests.cpu: "1500m"
    requests.memory: "750Mi"
    limits.cpu: "2000m"
    limits.memory: "1000Mi"
    pods: "6"